### ISSUE TITLE
Fix broken components of hosted docs

### ISSUE THREAD

**Issue by garrettjonesgoogle** [GoogleCloudPlatform/google-cloud-java#1578]
* The cobertura section is broken: http://googlecloudplatform.github.io/google-cloud-java/0.8.0/cobertura/index.html (all coverage is 0%, which is wrong)
* The license page is broken: http://googlecloudplatform.github.io/google-cloud-java/0.8.0/license.html

**Comment by lesv** [comment]
License was fixed in #1695

**Comment by lesv** [comment]
[Cobertura maven docs](http://www.mojohaus.org/cobertura-maven-plugin/plugin-info.html)

**Comment by lesv** [comment]
Having reviewed the docs and compared with the pom.xml, the configuration looks nothing like what our pom.xml does.

**Comment by garrettjonesgoogle** [comment]
@lesv what do you mean?

**Comment by shinfan** [comment]
The license is already fixed. I will take a look at the coverage.

**Comment by lesv** [comment]
Cortuba http://googlecloudplatform.github.io/google-cloud-java/0.12.0/cobertura/index.html still appears broken.  (I meant that when I looked at the maven docs vs. what we have in the pom.xml, I couldn't find anything that looked similar -- ie. it all needs to be redone.

**Comment by shinfan** [comment]
This issue should be fixed with next GCJ release

**Comment by garrettjonesgoogle** [comment]
http://googlecloudplatform.github.io/google-cloud-java/0.17.0/cobertura/index.html is working. Resolving issue.
