### ISSUE TITLE
Pub/Sub Publisher hangs unless submitted through an executor.

### ISSUE THREAD

**Issue by jabubake** [GoogleCloudPlatform/google-cloud-java#2150]
Note : See #2144 for auth workaround that is required, and independent of this issue.

```
  Publisher publisher = Publisher.defaultBuilder(topicName).build();
    PubsubMessage pubsubMessage =
        PubsubMessage.newBuilder().setData(ByteString.copyFromUtf8(message)).build();
    String messageId = publisher.publish(pubsubMessage).get();
```
hangs if run directly from a request.

This works only if executed using an `ExecutorService`. Users should n't be required to provide an executor to publish messages within a request.

**Comment by jabubake** [comment]
@lesv @ludoch FYI

**Comment by lesv** [comment]
This is wrong and it isn't required for [Cloud Bigtable](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/) to work.

**Comment by neozwu** [comment]
@ludoch for gae std java 8, what is the time limit for request thread ?  
In general, should we suggest users to use executors/threading for client lib on GAE? A lot of our code needs retry, which inherently uses executor and could take long time (longer than request thread could live ?)

**Comment by jabubake** [comment]
Note:  I was using manual scaling.

**Comment by lesv** [comment]
So what it appears you are doing is using the GAE API's (probably URLFetch), but on J8, you don't need to do that, just use normal Java IO). 

@eamonnmcmanus @ifigotin FYI

**Comment by lesv** [comment]
@garrettjonesgoogle FYI - this is kind of important to us.

**Comment by neozwu** [comment]
We haven't released a new version that fully supports GAE std J8. When I tested our lib on GAE std J8, I changed this [code](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-core-http/src/main/java/com/google/cloud/http/HttpTransportOptions.java#L61) to always use `NetHttpTransport`.
We should still keep URLfetch for J7 users.  
@ludoch / @ifigotin , is the recommended way to get GAE version at runtime is through
`System.getProperty("com.google.appengine.runtime.version")` ?

**Comment by lesv** [comment]
Java System Properties that may be of interest:
```
sun.boot.library.path	/base/jre8/lib/amd64
appengine.mail.filenamePreventsInlining	true
appengine.mail.supportExtendedAttachmentEncodings	true
com.google.appengine.application.id	lesv-003
java.runtime.version	1.8.0_112-google-v7-146844476-143772575
classpath.runtime-impl	/base/java8_runtime/runtime-impl.jar:/base/java8_runtime/runtime-impl-third-party.jar:/base/java8_runtime/runtime-appengine-api.jar
java.endorsed.dirs	/base/jre8/lib/endorsed
org.eclipse.jetty.util.log.class	com.google.apphosting.runtime.jetty9.JettyLogger
java.library.path	/base/java8_runtime:
classpath.prebundled	/base/java8_runtime/conscrypt.jar
com.google.appengine.application.version	20170614t130015.401974155730337826
java.specification.version	1.8
com.google.appengine.runtime.environment	Production
user.name	appengine
java.class.path	/base/java8_runtime/runtime-main.jar
classpath.api-map	1.0=/base/java8_runtime/api/appengine-api.jar
java.vm.specification.version	1.8
java.home	/base/jre8
java.version	1.8.0_112-google-v7
java.ext.dirs	/base/jre8/lib/ext:/usr/java/packages/lib/ext
```

**Comment by lesv** [comment]
@neozwu If I were you, I'd look at both "java.specification.version" == "1.8" and "com.google.appengine.runtime.environment" being present.

**Comment by eamonnmcmanus** [comment]
The main potential drawback with consulting java.specification.version is that people could be testing Java 7 apps using the dev_appserver running on JDK 8. We plan to define a system property that specifically tells you what runtime you have, but that hasn't happened yet. Meanwhile another possibility would be just to try to connect to some address (using `new Socket(...)`) or whatever, and see what happens.

**Comment by lesv** [comment]
@neozwu Any update?

**Comment by neozwu** [comment]
@eamonnmcmanus is there any estimate when the system property indicating runtime will exist ?

**Comment by lesv** [comment]
@neozwu @eamonnmcmanus and I were talking and he suggested that the Jetty version was probably the best indicator until we can get something else present.

If you look at the Java System Properties:  `org.eclipse.jetty.util.log.class`

When deployed on J8 it is:  `com.google.apphosting.runtime.jetty9.JettyLogger`
When running in DevAppServer: `com.google.appengine.development.jetty9.JettyLogger`

**Comment by lesv** [comment]
@neozwu any update - I seem to recall reviewing a PR yesterday or before on the auth repo?

**Comment by garrettjonesgoogle** [comment]
Provisionally marking P1 - maybe should be P0 because GAE std Java 8 is launched ( https://cloudplatform.googleblog.com/2017/06/Google-App-Engine-standard-now-supports-Java-8.html ).

**Comment by neozwu** [comment]
With this [merge](https://github.com/GoogleCloudPlatform/google-cloud-java/pull/2183), it should fix the http transport issue (to use the right http transport based on j7 or j8).

**Comment by jabubake** [comment]
@neozwu , @lesv  : I tried with 0.20.2-beta-SNAPSHOT, it still hangs when deployed (`mvn appengine:deploy`).

On local testing with `appengine:run`, this is what I ran into : 
`[INFO] GCLOUD: Jun 30, 2017 2:35:26 PM io.grpc.internal.ChannelExecutor drain
[INFO] GCLOUD: WARNING: Runnable threw exception in ChannelExecutor
[INFO] GCLOUD: java.lang.NullPointerException
[INFO] GCLOUD: 	at com.google.appengine.tools.development.RequestEndListenerHelper.getListeners(RequestEndListenerHelper.java:52)
[INFO] GCLOUD: 	at com.google.appengine.tools.development.RequestEndListenerHelper.register(RequestEndListenerHelper.java:39)
[INFO] GCLOUD: 	at com.google.appengine.tools.development.RequestThreadFactory$1$1.start(RequestThreadFactory.java:65)
[INFO] GCLOUD: 	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950)
[INFO] GCLOUD: 	at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1587)
[INFO] GCLOUD: 	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:334)
[INFO] GCLOUD: 	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
[INFO] GCLOUD: 	at io.grpc.internal.ManagedChannelImpl.rescheduleIdleTimer(ManagedChannelImpl.java:334)
[INFO] GCLOUD: 	at io.grpc.internal.ManagedChannelImpl.access$700(ManagedChannelImpl.java:83)
[INFO] GCLOUD: 	at io.grpc.internal.ManagedChannelImpl$2.handleNotInUse(ManagedChannelImpl.java:247)
[INFO] GCLOUD: 	at io.grpc.internal.InUseStateAggregator.updateObjectInUse(InUseStateAggregator.java:60)
[INFO] GCLOUD: 	at io.grpc.internal.ManagedChannelImpl$1.transportInUse(ManagedChannelImpl.java:198)
[INFO] GCLOUD: 	at io.grpc.internal.DelayedClientTransport$2.run(DelayedClientTransport.java:116)
[INFO] GCLOUD: 	at io.grpc.internal.ChannelExecutor.drain(ChannelExecutor.java:87)
[INFO] GCLOUD: 	at io.grpc.internal.InternalSubchannel$TransportListener.transportReady(InternalSubchannel.java:458)
[INFO] GCLOUD: 	at io.grpc.netty.ClientTransportLifecycleManager.notifyReady(ClientTransportLifecycleManager.java:58)
[INFO] GCLOUD: 	at io.grpc.netty.NettyClientHandler$FrameListener.onSettingsRead(NettyClientHandler.java:646)
[INFO] GCLOUD: 	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onSettingsRead(DefaultHttp2ConnectionDecoder.java:412)
[INFO] GCLOUD: 	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$PrefaceFrameListener.onSettingsRead(DefaultHttp2ConnectionDecoder.java:624)
[INFO] GCLOUD: 	at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onSettingsRead(Http2InboundFrameLogger.java:93)
[INFO] GCLOUD: 	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readSettingsFrame(DefaultHttp2FrameReader.java:542)
[INFO] GCLOUD: 	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:263)
[INFO] GCLOUD: 	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
[INFO] GCLOUD: 	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
[INFO] GCLOUD: 	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:116)
[INFO] GCLOUD: 	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:353)
[INFO] GCLOUD: 	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:224)
[INFO] GCLOUD: 	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:413)
[INFO] GCLOUD: 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
[INFO] GCLOUD: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
[INFO] GCLOUD: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[INFO] GCLOUD: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[INFO] GCLOUD: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[INFO] GCLOUD: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[INFO] GCLOUD: 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1267)
[INFO] GCLOUD: 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1078)
[INFO] GCLOUD: 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
[INFO] GCLOUD: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
[INFO] GCLOUD: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[INFO] GCLOUD: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[INFO] GCLOUD: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[INFO] GCLOUD: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[INFO] GCLOUD: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
[INFO] GCLOUD: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[INFO] GCLOUD: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[INFO] GCLOUD: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
[INFO] GCLOUD: 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
[INFO] GCLOUD: 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
[INFO] GCLOUD: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
[INFO] GCLOUD: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
[INFO] GCLOUD: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
[INFO] GCLOUD: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
[INFO] GCLOUD: 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
[INFO] GCLOUD: 	at java.lang.Thread.run(Thread.java:745)
`

**Comment by garrettjonesgoogle** [comment]
@tcoffee-google this is another important issue to look at.

**Comment by neozwu** [comment]
Another report of this problem https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2275. It seems there are more investigations [here](https://groups.google.com/forum/#!msg/google-appengine/2UTg4Eqskyk/PbqYEK3GAAAJ), and it indeed suggests running in requestThread causes this issue.

**Comment by jabubake** [comment]
@neozwu :  [Pub/Sub on App engine](https://github.com/GoogleCloudPlatform/java-docs-samples/blob/appengine-pubsub/appengine-java8/pubsub/src/main/java/com/example/appengine/pubsub/) shows submission using an executor

**Comment by hienle-hps** [comment]
@jabubake Is this Executor usage a temporary workaround or is it the idiomatic recommendation?

**Comment by jabubake** [comment]
It is not a workaround or an idiomatic recommendation. Just providing @neozwu the actual code for troubleshooting.

**Comment by neozwu** [comment]
This problem is also reported in #2275 (Pub/Sub API) and #2306 (Spanner API).  I'm going to close this issue and use #2275 to update status.
