### ISSUE TITLE
Maven dependency issues

### ISSUE THREAD

**Issue by dconnelly** [GoogleCloudPlatform/google-cloud-java#2196]
Looks like module dependencies are mixing different versions of api-common:
```
Dependency convergence error for com.google.api:api-common:1.1.0 paths to dependency are:
+-astro:astro-admin-server:1.0-SNAPSHOT
  +-com.google.cloud:google-cloud-bigquery:0.20.0-beta
    +-com.google.cloud:google-cloud-core:1.2.0
      +-com.google.api:api-common:1.1.0
and
+-astro:astro-admin-server:1.0-SNAPSHOT
  +-com.google.cloud:google-cloud-bigquery:0.20.0-beta
    +-com.google.cloud:google-cloud-core:1.2.0
      +-com.google.api:gax:1.3.1
        +-com.google.api:api-common:1.1.0
and
+-astro:astro-admin-server:1.0-SNAPSHOT
  +-com.google.cloud:google-cloud-bigquery:0.20.0-beta
    +-com.google.cloud:google-cloud-core:1.2.0
      +-com.google.api.grpc:proto-google-iam-v1:0.1.11
        +-com.google.api:api-common:1.0.0-rc1
```
You should be able to enforce consistent dependencies with the maven dependency plugin before publishing artifacts.

**Comment by shinfan** [comment]
Can you try to use com.google.cloud:google-cloud-bigquery:0.20.1-beta? This issue should have been solved in the latest version.

**Comment by shinfan** [comment]
Closing this issue for now. Please reopen it if it is not solved.

**Comment by dconnelly** [comment]
Hi Michael,

Still seeing other dependency issues with 0.20.1-beta when trying to mix with other latest Google API components:

google-cloud-core-http is using an older version of google-api-client:

```
[WARNING] 
Dependency convergence error for com.google.api-client:google-api-client:1.22.0 paths to dependency are:
+-astro:astro-admin-server:1.0-SNAPSHOT
  +-astro:astro-mail-core:1.0-SNAPSHOT
    +-astro:astro-common-mail:1.0-SNAPSHOT
      +-com.google.apis:google-api-services-gmail:v1-rev65-1.22.0
        +-com.google.api-client:google-api-client:1.22.0
and
+-astro:astro-admin-server:1.0-SNAPSHOT
  +-astro:astro-mail-core:1.0-SNAPSHOT
    +-astro:astro-common-mail:1.0-SNAPSHOT
      +-com.google.apis:google-api-services-pubsub:v1-rev356-1.22.0
        +-com.google.api-client:google-api-client:1.22.0
and
+-astro:astro-admin-server:1.0-SNAPSHOT
  +-astro:astro-mail-core:1.0-SNAPSHOT
    +-astro:astro-common-mail:1.0-SNAPSHOT
      +-com.google.apis:google-api-services-calendar:v3-rev245-1.22.0
        +-com.google.api-client:google-api-client:1.22.0
and
+-astro:astro-admin-server:1.0-SNAPSHOT
  +-com.google.cloud:google-cloud-bigquery:0.20.1-beta
    +-com.google.cloud:google-cloud-core-http:1.2.1
      +-com.google.api-client:google-api-client:1.21.0
and
+-astro:astro-admin-server:1.0-SNAPSHOT
  +-com.google.cloud:google-cloud-bigquery:0.20.1-beta
    +-com.google.apis:google-api-services-bigquery:v2-rev347-1.22.0
      +-com.google.api-client:google-api-client:1.22.0
```
Also dependency on com.google.auth:google-auth-library-oauth2-http:0.7.0 might be an issue:
```
[WARNING] 
Dependency convergence error for com.google.http-client:google-http-client:1.19.0 paths to dependency are:
+-astro:astro-admin-server:1.0-SNAPSHOT
  +-com.google.cloud:google-cloud-bigquery:0.20.1-beta
    +-com.google.cloud:google-cloud-core-http:1.2.1
      +-com.google.auth:google-auth-library-oauth2-http:0.7.0
        +-com.google.http-client:google-http-client:1.19.0
and
+-astro:astro-admin-server:1.0-SNAPSHOT
  +-com.google.cloud:google-cloud-bigquery:0.20.1-beta
    +-com.google.cloud:google-cloud-core-http:1.2.1
      +-com.google.auth:google-auth-library-oauth2-http:0.7.0
        +-com.google.http-client:google-http-client-jackson2:1.19.0
          +-com.google.http-client:google-http-client:1.19.0
and
+-astro:astro-admin-server:1.0-SNAPSHOT
  +-com.google.cloud:google-cloud-bigquery:0.20.1-beta
    +-com.google.cloud:google-cloud-core-http:1.2.1
      +-com.google.http-client:google-http-client:1.21.0
and
+-astro:astro-admin-server:1.0-SNAPSHOT
  +-com.google.cloud:google-cloud-bigquery:0.20.1-beta
    +-com.google.cloud:google-cloud-core-http:1.2.1
      +-com.google.oauth-client:google-oauth-client:1.21.0
        +-com.google.http-client:google-http-client:1.21.0
and
+-astro:astro-admin-server:1.0-SNAPSHOT
  +-com.google.cloud:google-cloud-bigquery:0.20.1-beta
    +-com.google.cloud:google-cloud-core-http:1.2.1
      +-com.google.http-client:google-http-client-appengine:1.21.0
        +-com.google.http-client:google-http-client:1.21.0
and
+-astro:astro-admin-server:1.0-SNAPSHOT
  +-com.google.cloud:google-cloud-bigquery:0.20.1-beta
    +-com.google.cloud:google-cloud-core-http:1.2.1
      +-com.google.http-client:google-http-client-jackson:1.21.0
        +-com.google.http-client:google-http-client:1.21.0
```
Might be worth providing a Maven BOM with consistent dependencies to ease development across the various Google Java API clients.

**Comment by dconnelly** [comment]
Unfortunately, I can't re-open this issue but I will file a new one if you want.

**Comment by garrettjonesgoogle** [comment]
@dconnelly Regarding this statement:

> You should be able to enforce consistent dependencies with the maven dependency plugin before publishing artifacts.

We do have dependencyConvergence enabled, but that doesn't take effect for consumers of our library.

**Comment by dconnelly** [comment]
Fair enough, but I get dependency convergence issues even with the most basic POM file with only bigquery as a dependency:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>test</groupId>
  <artifactId>test</artifactId>
  <version>1.0-SNAPSHOT</version>
  <dependencies>
    <dependency>
      <groupId>com.google.cloud</groupId>
      <artifactId>google-cloud-bigquery</artifactId>
      <version>0.20.1-beta</version>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-enforcer-plugin</artifactId>
        <executions>
          <execution>
            <id>enforce</id>
            <goals>
              <goal>enforce</goal>
            </goals>
            <configuration>
              <rules>
                <dependencyConvergence/>
              </rules>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
```
For example, google-oauth-client depends on an older version of jsr305 which conflicts with google-cloud-core.

**Comment by garrettjonesgoogle** [comment]
Yes, you can get pretty close by using `<requireUpperBoundDeps/>` (see https://github.com/grpc/grpc-java/blob/424eeea/examples/pom.xml#L82 for an example). What it basically does is check that maven selects the latest version of each dependency; when maven doesn't select the latest, the build will fail, and you will have to override that particular package to the latest version. If maven happens to pick the latest version for all of your dependencies, it will do nothing. Will that work for you?

**Comment by garrettjonesgoogle** [comment]
In version 0.21.0-beta of google-cloud-bigquery, I fixed the set of versions pulled in, and added `<requireUpperBoundDeps/>` to our own repo, so this should be fixed now.
